openapi: 3.1.0
info: 
  title: Fédération de collectivités agricoles
  version: 1.0.0

servers: 
  - url: http://localhost:8080 

paths: 
  /collectivities:
    post: 
      description: Create a new collectivity
      operationId: newCollectivities

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Collectivities'

      responses:
        '201':
          description: Collectivity created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Collectivities'
                

        '400':
          description: Collectivity creation not satisfied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example: 
                message: You must complete the informations about the collectivity
                status: 400

        '403':
          description: Collectivity creation not authorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example: 
                message: The new Collectivity need to follow all the requirement
                
  /collectivities/{id}/members: 
    post:
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        example: 12
      description: Member inscription
      tags: 
        - Members 
      requestBody: 
        required: true
        content:
          application/json: 
            schema:
              type : object
              properties:
                sponsorId:
                  type: integer
                NewMemberInformation: 
                  $ref: "#/components/schemas/Members"
                Transaction: 
                  $ref: "#/components/schemas/Transaction"
            example:
              sponsorId: 12
              NewMemberInformation: 
                id: 134
                name: Rivo Andrianantenaina
                birthdate: 1988-11-02
                gender: male
                address: Lot II M 68 Bis, Ambohimanarina, Antananarivo 101
                occupation: collector
                phone: +261 34 12 345 67
                email: rivo.andria@example.mg
                collectivityId: 3
              Transaction:
                references: PAR-MDG-20260416-089
                amount: 50000
                payment: Orange_money
                status: success
                transactionDate: 2026-04-16T09:15:22.123Z
      responses: 
        '201':
          description: Welcome to our collectivity
          content: 
            application/json:
              schema: 
                type: object
                properties: 
                  sponsorId:
                    type: integer
                  NewMemberInformations: 
                    $ref: "#/components/schemas/Members"
                  Transaction: 
                    $ref: "#/components/schemas/Transaction"
              example:
                sponsorId: 12
                NewMemberInformation: 
                  id: 134
                  name: Rivo Andrianantenaina
                  birthdate: 1988-11-02
                  gender: male
                  address: Lot II M 68 Bis, Ambohimanarina, Antananarivo 101
                  occupation: teacher
                  phone: +261 34 12 345 67
                  email: rivo.andria@example.mg
                  collectivityId: 3
                Transaction:
                  references: PAR-MDG-20260416-089
                  amount: 50000
                  payment: Orange_money
                  status: success
                  transactionDate: 2026-04-16T09:15:22.123Z
                       
        '400': 
          description: Information incomplete
          content: 
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example: 
                message: You must complete all the informations about the new member
                status: 400
        '403':
          description: Admission not authorized 
          content: 
            application/json:
              schema: 
                $ref: "#/components/schemas/Error"
              example: 
                message: Your profile does not meet the requirements for membership
                status: 403
  /members/{id}:
    put:
      description: Change Member informations or collective
      tags: 
        - Members
      parameters:
        - name: id 
          in: path
          required: true
          schema: 
            type: integer
            example: 17
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              $ref: "#/components/schemas/Members"
            example: 
              id: 17
              name: Miora Faniry Razafimahatratra
              birthdate: 1992-03-18
              gender: female
              address: Lot VA 15 Ter, Andoharanofotsy, Antananarivo 102
              occupation: collector
              phone: +261 32 98 765 43
              email: miora.faniry@example.mg
              collectivityId: 3

      responses: 
        '200':
          description: Member information updated
          content: 
            application/json:
              schema: 
                $ref: "#/components/schemas/Members"
              example: 
                id: 17
                name: Miora Faniry Razafimahatratra
                birthdate: 1992-03-18
                gender: female
                address: Lot VA 15 Ter,   Andoharanofotsy, Antananarivo 102
                occupation: collector
                phone: +261 32 98 765 43
                email: miora.faniry@example.mg
                collectivityId: 3
               

        '404':
          description: Member not found
          content: 
            application/json:
              schema: 
                $ref: "#/components/schemas/Error"
              example: 
                message: The member from id={id} is not found
                status: 404
    delete: 
      tags:
       - Members
      description: Do you want to leave 
      parameters: 
        - name : id
          in: path
          required: true
          schema: 
            type: integer
            example: 17
      responses: 
        '200': 
          description: You left 
          content: 
            application/json: 
              schema: 
                $ref: "#/components/schemas/Members"
              example: 
                id: 17
                name: Miora Faniry Razafimahatratra
                birthdate: 1992-03-18
                gender: female
                address: Lot VA 15 Ter,   Andoharanofotsy, Antananarivo 102
                occupation: collector
                phone: +261 32 98 765 43
                email: miora.faniry@example.mg
            
        '400':
          description: Member not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example: 
                message: The member from id={id} is not found
                status: 400

  /collectivities/{id}/accounts:
    post:
      description: add treasury account
      operationId: createCollectivityAccount

      parameters:
      - name: id
        in: path
        required: true
        schema: 
          type: integer
      
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Account'
        required: true

      responses:
        '201':
          description: account created 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'

        '404':
          description: Collectivity.id={id} is not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                message: Collectivity.id=19 is not found
                status: 404
    get:
      description: get account 
      operationId: getCollectivityAccounts 
      
      parameters:
      - name: id
        in: path
        required: true
        schema: 
          type: integer 

      responses:
        '200':
          description: find account
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        
        '404':
          description: Collectivity.id={id} is not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                message: Collectivity.id=19 is not found
                status: 404
  
  /activities/{id}/attendance:
    post:
      description: attendance record provided by id
      operationId: recordAttendance

      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Attendance"

      responses:
        '201':
          description: attendance registration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Attendance'
               

        '404':
          description: activity or member not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
                example: 
                  message: member.id=14 is not found
                  status: 404

  /members/{id}/attendance-rate:
    get:
      description: get attendance rate of a member for a period
      operationId: getAttendanceRate
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer

        - name: from
          in: query
          required: true
          schema:
            type: string
            format: date

        - name: to
          in: query
          required: true
          schema:
            type: string
            format: date

      responses:
        "200":
          description: attendance rate calculated
          content:
            application/json:
              schema:
                type: object
                properties:
                  attendanceRate:
                    type: number
                    format: float

        "400":
          description: missing queryParameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
                example: 
                  message: the parameters 'to' and 'from' are not present
                  status: 400
        '404':
          description:  member not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
                example:
                  message: member.id=14 is not found
                  status: 404
    



  
          


components:
  schemas:

    Collectivities:
      type: object
      properties:
        id:
          type: integer
        nom:
          type: string
        ville:
          type: string
        speciality:
          type: string
        creationDateTime:
          type: string
          format: date-time
        
    Members:
      type: object
      properties:
        id: 
          type: integer
        name: 
          type: string
        birthdate: 
          type: string
          format: date
        gender: 
          type: string
          enum: 
            - male
            - female
        address: 
          type: string
        occupation: 
          type: string
        phone: 
          type: string
        email: 
          type: string
          format: email
        collectivityId: 
          type: integer

    Positions:
      type: string
      enum: 
          - PRESIDENT
          - VICE PRESIDENT 
          - TREASURER 
          - SECREATARY
          - SENIOR_MEMBER
          - JUNIOR_MEMBER
    Mandate: 
      type: object
      required: 
        - id
        - collectivityId
        - memberId
        - position
        - startDate
        - endDate
      properties: 
        id: 
          type: integer
        collectivityId: 
          type: integer
        memberId: 
          type: integer
        position: 
          $ref: "#/components/schemas/Positions"
        startDate: 
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time

       
    Transaction: 
      required:
        - references
        - amount
        - status
      type: object
      properties:
        references: 
          type: string
        amount:
          type: number
        payment: 
          type: string
        status: 
          type: string
          enum: 
            - SUCCESS
            - FAILURE
        transactionDate: 
          type: string
          format: date-time   
    Error:
      type: object
      properties:
        message:
          type: string
        status:
          type: integer

    Account:
      type: object
      properties:
        id:
          type: integer
        typeAccount:
          type: string
          enum: ["BRED", "MCB", "BMOI", "BOA", "BGFI", "AFG", "ACCÈS BANQUE", "BAOBAB", "SIPEM"]
        titulaireName: 
          type: string
        accountDetail:
          $ref: '#/components/schemas/AccountDetail'

    AccountDetail:    
      type: object
      properties:
        bankCode:
          type: string
          minLength: 5
          maxLength: 5
        boxCode:
          type: string
          minLength: 5
          maxLength: 5
        accountNumber:
          type: string
          minLength: 11
          maxLength: 11
        RIBkey:
          type: string
          minLength: 2
          maxLength: 2
    
  
    Attendance:
      type: object
      properties:
        memberId:
          type: integer
        activityId:
          type: integer
        present:
          type: boolean
        justification:
          type: string

    AttendanceRate:
      type: object
      properties:
        attendanceRate:
          type: number
          format: float

   
  
        
                  